### ISSUE TITLE
UI problems with cata

### ISSUE THREAD

**Issue by Schimea** [rubenzantingh/MultiLanguage#2]
Hello, I’m using your addon for studying Portuguese, thanks for that help. Since Cata I have the problem, that the quest log shows the “target model” next to the original quest text. Unfortunately, the translation is right behind the target model, so I’m not able to read the translation anymore. Do you have any idea how I can solve that?

**Comment by rubenzantingh** [comment]
Hey Schimea,

First of all, I'm happy that you're enjoying the addon and that you've taken the time to reach out. The issue you mentioned is also something I've recently noticed. Because I don't play the game as often anymore, there will be some cases where bugs like this go unnoticed. So if you see anything else don't hesitate to reach out.

I will try to resolve the issue you're having somewhere this week, I will be sure to inform you here when I release the new version.

**Comment by rubenzantingh** [comment]
Hey Schimea,

I am currently releasing 'cata-v1.0.6'. It should be fixed in this version, please let me know!

**Comment by Schimea** [comment]
Hey, 
thanks for the fast fix. Its above the target window now. Works perfect. Thanks. :)
