### ISSUE TITLE
Cannot translate gassip text

### ISSUE THREAD

**Issue by JerryHol** [rubenzantingh/MultiLanguage#3]
Hello,My native language is Chinese, I use this plugin to learn English,This plugin is really helpful for me, appreciate all your work!
I found a problem. When I found an NPC to complete a quest, the text was not translated, only the task title was translated.But the English mode displayed normally. Do you have any idea how I can solve that?
![20240618185511](https://github.com/rubenzantingh/MultiLanguage/assets/118865508/6dde2030-3cac-4100-866e-79924e711c61)
![20240618185552](https://github.com/rubenzantingh/MultiLanguage/assets/118865508/eba7105d-e9df-4151-b9b2-6522e3e7f152)

**Comment by rubenzantingh** [comment]
Hey JerryHol,

Thanks a lot for using the addon, I'm glad you're finding it useful! I've tested the issue you've encountered and I get the same thing. What I've found is that the quest has no completion or progress text on wowhead, which is the source for the data in the addon. You can see it [here](https://www.wowhead.com/classic/cn/quest=789/%E5%B7%A5%E8%9D%8E%E7%9A%84%E5%B0%BE%E5%B7%B4). Where for other languages like [Korean](https://www.wowhead.com/classic/ko/quest=789/%EC%A0%84%EA%B0%88%EC%9D%98-%EB%8F%85%EC%B9%A8) it is present. 

The API that Blizzard provides also doesn't have this data, which leaves me very little alternative. Because of the reasons above I am unable to provide a fix a this time. I will be monitoring the data for the Chinese language and hope that this will become available in the future. 

I'm sorry I couldn't help you this time. However, if you do encounter any other issues in the future, I really appreciate the report.
